# Use a Node.js base image
FROM node:16-alpine3.16

# Set the working directory
WORKDIR /app

# Copy .json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code
COPY . ./

# Expose the necessary ports
EXPOSE 3000

# Start the development server
CMD ["npm", "start"]
